/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace JobContract {
  export type JobStruct = {
    id: BigNumberish;
    employer: AddressLike;
    organizationName: string;
    jobTitle: string;
    jobDescription: string;
    budget: BigNumberish;
    status: BigNumberish;
    jobType: BigNumberish;
    workMode: BigNumberish;
    deadline: BigNumberish;
    categories: string[];
    postedAt: BigNumberish;
    logoIpfsCid: string;
  };

  export type JobStructOutput = [
    id: bigint,
    employer: string,
    organizationName: string,
    jobTitle: string,
    jobDescription: string,
    budget: bigint,
    status: bigint,
    jobType: bigint,
    workMode: bigint,
    deadline: bigint,
    categories: string[],
    postedAt: bigint,
    logoIpfsCid: string
  ] & {
    id: bigint;
    employer: string;
    organizationName: string;
    jobTitle: string;
    jobDescription: string;
    budget: bigint;
    status: bigint;
    jobType: bigint;
    workMode: bigint;
    deadline: bigint;
    categories: string[];
    postedAt: bigint;
    logoIpfsCid: string;
  };

  export type ApplicationStruct = {
    jobId: BigNumberish;
    applicant: AddressLike;
    status: BigNumberish;
    resumeIpfsCid: string;
  };

  export type ApplicationStructOutput = [
    jobId: bigint,
    applicant: string,
    status: bigint,
    resumeIpfsCid: string
  ] & {
    jobId: bigint;
    applicant: string;
    status: bigint;
    resumeIpfsCid: string;
  };
}

export interface JobContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "EMPLOYER_ROLE"
      | "JOB_MANAGER_ROLE"
      | "applyForJob"
      | "changeJobStatus"
      | "changeJobStatusAsAdmin"
      | "createJob"
      | "getAllJobs"
      | "getApplicationsForApplicant"
      | "getApplicationsForJob"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "jobs"
      | "renounceRole"
      | "revokeRole"
      | "serviceFeePercent"
      | "setServiceFee"
      | "supportsInterface"
      | "updateApplicationStatus"
      | "updateApplicationStatusAsAdmin"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApplicationStatusChanged"
      | "ApplicationSubmitted"
      | "JobCreated"
      | "JobStatusChanged"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "ServiceFeeChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMPLOYER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "JOB_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyForJob",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeJobStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeJobStatusAsAdmin",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string[],
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllJobs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApplicationsForApplicant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getApplicationsForJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "serviceFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setServiceFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateApplicationStatus",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateApplicationStatusAsAdmin",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMPLOYER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "JOB_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyForJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeJobStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeJobStatusAsAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAllJobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getApplicationsForApplicant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApplicationsForJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "serviceFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setServiceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateApplicationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateApplicationStatusAsAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace ApplicationStatusChangedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    applicant: AddressLike,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    applicant: string,
    newStatus: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    applicant: string;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApplicationSubmittedEvent {
  export type InputTuple = [jobId: BigNumberish, applicant: AddressLike];
  export type OutputTuple = [jobId: bigint, applicant: string];
  export interface OutputObject {
    jobId: bigint;
    applicant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    employer: AddressLike,
    jobTitle: string,
    budget: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    employer: string,
    jobTitle: string,
    budget: bigint
  ];
  export interface OutputObject {
    id: bigint;
    employer: string;
    jobTitle: string;
    budget: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobStatusChangedEvent {
  export type InputTuple = [id: BigNumberish, newStatus: BigNumberish];
  export type OutputTuple = [id: bigint, newStatus: bigint];
  export interface OutputObject {
    id: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceFeeChangedEvent {
  export type InputTuple = [newFeePercent: BigNumberish];
  export type OutputTuple = [newFeePercent: bigint];
  export interface OutputObject {
    newFeePercent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface JobContract extends BaseContract {
  connect(runner?: ContractRunner | null): JobContract;
  waitForDeployment(): Promise<this>;

  interface: JobContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EMPLOYER_ROLE: TypedContractMethod<[], [string], "view">;

  JOB_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  applyForJob: TypedContractMethod<
    [jobId: BigNumberish, resumeIpfsCid: string],
    [void],
    "nonpayable"
  >;

  changeJobStatus: TypedContractMethod<
    [jobId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  changeJobStatusAsAdmin: TypedContractMethod<
    [jobId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  createJob: TypedContractMethod<
    [
      organizationName: string,
      jobTitle: string,
      jobDescription: string,
      budget: BigNumberish,
      jobType: BigNumberish,
      workMode: BigNumberish,
      deadline: BigNumberish,
      categories: string[],
      logoIpfsCid: string
    ],
    [bigint],
    "nonpayable"
  >;

  getAllJobs: TypedContractMethod<[], [JobContract.JobStructOutput[]], "view">;

  getApplicationsForApplicant: TypedContractMethod<
    [applicant: AddressLike],
    [JobContract.ApplicationStructOutput[]],
    "view"
  >;

  getApplicationsForJob: TypedContractMethod<
    [jobId: BigNumberish],
    [JobContract.ApplicationStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        employer: string;
        organizationName: string;
        jobTitle: string;
        jobDescription: string;
        budget: bigint;
        status: bigint;
        jobType: bigint;
        workMode: bigint;
        deadline: bigint;
        postedAt: bigint;
        logoIpfsCid: string;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  serviceFeePercent: TypedContractMethod<[], [bigint], "view">;

  setServiceFee: TypedContractMethod<
    [_newFeePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateApplicationStatus: TypedContractMethod<
    [jobId: BigNumberish, applicant: AddressLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateApplicationStatusAsAdmin: TypedContractMethod<
    [jobId: BigNumberish, applicant: AddressLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EMPLOYER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "JOB_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "applyForJob"
  ): TypedContractMethod<
    [jobId: BigNumberish, resumeIpfsCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeJobStatus"
  ): TypedContractMethod<
    [jobId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeJobStatusAsAdmin"
  ): TypedContractMethod<
    [jobId: BigNumberish, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [
      organizationName: string,
      jobTitle: string,
      jobDescription: string,
      budget: BigNumberish,
      jobType: BigNumberish,
      workMode: BigNumberish,
      deadline: BigNumberish,
      categories: string[],
      logoIpfsCid: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllJobs"
  ): TypedContractMethod<[], [JobContract.JobStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getApplicationsForApplicant"
  ): TypedContractMethod<
    [applicant: AddressLike],
    [JobContract.ApplicationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getApplicationsForJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [JobContract.ApplicationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        employer: string;
        organizationName: string;
        jobTitle: string;
        jobDescription: string;
        budget: bigint;
        status: bigint;
        jobType: bigint;
        workMode: bigint;
        deadline: bigint;
        postedAt: bigint;
        logoIpfsCid: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "serviceFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setServiceFee"
  ): TypedContractMethod<[_newFeePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateApplicationStatus"
  ): TypedContractMethod<
    [jobId: BigNumberish, applicant: AddressLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateApplicationStatusAsAdmin"
  ): TypedContractMethod<
    [jobId: BigNumberish, applicant: AddressLike, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ApplicationStatusChanged"
  ): TypedContractEvent<
    ApplicationStatusChangedEvent.InputTuple,
    ApplicationStatusChangedEvent.OutputTuple,
    ApplicationStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "ApplicationSubmitted"
  ): TypedContractEvent<
    ApplicationSubmittedEvent.InputTuple,
    ApplicationSubmittedEvent.OutputTuple,
    ApplicationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "JobStatusChanged"
  ): TypedContractEvent<
    JobStatusChangedEvent.InputTuple,
    JobStatusChangedEvent.OutputTuple,
    JobStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceFeeChanged"
  ): TypedContractEvent<
    ServiceFeeChangedEvent.InputTuple,
    ServiceFeeChangedEvent.OutputTuple,
    ServiceFeeChangedEvent.OutputObject
  >;

  filters: {
    "ApplicationStatusChanged(uint256,address,uint8)": TypedContractEvent<
      ApplicationStatusChangedEvent.InputTuple,
      ApplicationStatusChangedEvent.OutputTuple,
      ApplicationStatusChangedEvent.OutputObject
    >;
    ApplicationStatusChanged: TypedContractEvent<
      ApplicationStatusChangedEvent.InputTuple,
      ApplicationStatusChangedEvent.OutputTuple,
      ApplicationStatusChangedEvent.OutputObject
    >;

    "ApplicationSubmitted(uint256,address)": TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;
    ApplicationSubmitted: TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;

    "JobCreated(uint256,address,string,uint256)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "JobStatusChanged(uint256,uint8)": TypedContractEvent<
      JobStatusChangedEvent.InputTuple,
      JobStatusChangedEvent.OutputTuple,
      JobStatusChangedEvent.OutputObject
    >;
    JobStatusChanged: TypedContractEvent<
      JobStatusChangedEvent.InputTuple,
      JobStatusChangedEvent.OutputTuple,
      JobStatusChangedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "ServiceFeeChanged(uint256)": TypedContractEvent<
      ServiceFeeChangedEvent.InputTuple,
      ServiceFeeChangedEvent.OutputTuple,
      ServiceFeeChangedEvent.OutputObject
    >;
    ServiceFeeChanged: TypedContractEvent<
      ServiceFeeChangedEvent.InputTuple,
      ServiceFeeChangedEvent.OutputTuple,
      ServiceFeeChangedEvent.OutputObject
    >;
  };
}
