
import type { Job } from './types';

export const jobs: Job[] = [
  {
    id: '1',
    title: 'Senior Solidity Developer',
    company: {
      name: 'ChainSecure',
      logoUrl: 'https://picsum.photos/seed/10/100/100',
      logoBg: 'bg-indigo-500',
      logoIpfsCid: '',
    },
    description: 'We are looking for a Senior Solidity Developer to build and maintain our DeFi protocols. You will be responsible for writing high-quality, secure smart contracts.',
    budget: 15,
    currency: 'ETH',
    deadline: '2024-08-30',
    tags: ['Solidity', 'Blockchain', 'DeFi', 'Hardhat'],
    postedAt: '2024-07-15T10:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266',
  },
  {
    id: '2',
    title: 'Frontend Engineer (Web3)',
    company: {
      name: 'CryptoPunks',
      logoUrl: 'https://picsum.photos/seed/11/100/100',
      logoBg: 'bg-pink-500',
      logoIpfsCid: '',
    },
    description: 'Join our team to build the next generation of NFT marketplaces. Strong experience with React, ethers.js, and wallet integrations is required.',
    budget: 12,
    currency: 'ETH',
    deadline: '2024-09-15',
    tags: ['Frontend', 'React', 'Ethers.js', 'Web3'],
    postedAt: '2024-07-20T14:30:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x70997970c51812dc3a010c7d01b50e0d17dc79c8',
  },
  {
    id: '3',
    title: 'Full-Stack Blockchain Developer',
    company: {
      name: 'Decentralized Inc.',
      logoUrl: 'https://picsum.photos/seed/12/100/100',
      logoBg: 'bg-green-500',
      logoIpfsCid: '',
    },
    description: 'Seeking a versatile developer to work on both our smart contracts and the frontend that interacts with them. Experience with Node.js and IPFS is a plus.',
    budget: 18,
    currency: 'ETH',
    deadline: '2024-08-25',
    tags: ['Full-Stack', 'Solidity', 'React', 'Node.js', 'IPFS'],
    postedAt: '2024-07-18T09:00:00Z',
    location: 'Global',
    status: 'InProgress',
    userId: '0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266',
  },
  {
    id: '4',
    title: 'Smart Contract Auditor',
    company: {
      name: 'Guardian Audits',
      logoUrl: 'https://picsum.photos/seed/13/100/100',
      logoBg: 'bg-red-500',
      logoIpfsCid: '',
    },
    description: 'We need an experienced Smart Contract Auditor to review and secure our clients\' codebases. A deep understanding of EVM vulnerabilities is essential.',
    budget: 20,
    currency: 'ETH',
    deadline: '2024-09-01',
    tags: ['Security', 'Audit', 'Solidity', 'EVM'],
    postedAt: '2024-07-22T11:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc',
  },
  {
    id: '5',
    title: 'Lead Backend Engineer (The Graph)',
    company: {
      name: 'IndexerFi',
      logoUrl: 'https://picsum.photos/seed/14/100/100',
      logoBg: 'bg-yellow-500',
      logoIpfsCid: '',
    },
    description: 'Lead our backend team to build and optimize subgraphs for various DeFi protocols. You will be instrumental in making on-chain data accessible.',
    budget: 16,
    currency: 'ETH',
    deadline: '2024-09-10',
    tags: ['Backend', 'The Graph', 'GraphQL', 'Node.js'],
    postedAt: '2024-07-21T16:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x90f79bf6eb2c4f870365e785982e1f101e93b906',
  },
    {
    id: '6',
    title: 'Web3 Community Manager',
    company: {
      name: 'DAOverse',
      logoUrl: 'https://picsum.photos/seed/15/100/100',
      logoBg: 'bg-cyan-500',
      logoIpfsCid: '',
    },
    description: 'Engage and grow our community of developers and users. You will be the face of our DAO, managing social channels and organizing events.',
    budget: 8,
    currency: 'ETH',
    deadline: '2024-08-20',
    tags: ['Community', 'Marketing', 'DAO'],
    postedAt: '2024-07-25T08:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x15d34aaf54267db7d7c367839aaf71a00a2c6a65',
  },
  {
    id: '7',
    title: 'Rust Engineer for Solana',
    company: {
      name: 'Solana Labs',
      logoUrl: 'https://picsum.photos/seed/16/100/100',
      logoBg: 'bg-purple-500',
      logoIpfsCid: '',
    },
    description: 'Develop high-performance programs for the Solana blockchain. Proficiency in Rust is a must.',
    budget: 22,
    currency: 'ETH',
    deadline: '2024-09-05',
    tags: ['Blockchain', 'Rust', 'Solana'],
    postedAt: '2024-07-26T10:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x9965507d1a55bcc2695c58ba16fb37d819b0a4dc',
  },
  {
    id: '8',
    title: 'DevOps Engineer (Web3)',
    company: {
      name: 'InfraChain',
      logoUrl: 'https://picsum.photos/seed/17/100/100',
      logoBg: 'bg-orange-500',
      logoIpfsCid: '',
    },
    description: 'Manage and scale our blockchain infrastructure. Experience with Kubernetes, Docker, and cloud platforms is required.',
    budget: 14,
    currency: 'ETH',
    deadline: '2024-09-12',
    tags: ['DevOps', 'Kubernetes', 'Web3'],
    postedAt: '2024-07-27T11:00:00Z',
    location: 'New York, NY',
    status: 'Open',
    userId: '0x976ea74026e726554db657fa54763abd0c3a0aa9',
  },
  {
    id: '9',
    title: 'Junior Smart Contract Developer',
    company: {
      name: 'DeFi Start',
      logoUrl: 'https://picsum.photos/seed/18/100/100',
      logoBg: 'bg-teal-500',
      logoIpfsCid: '',
    },
    description: 'An entry-level position for a developer passionate about blockchain. You will learn to write and deploy smart contracts under supervision.',
    budget: 6,
    currency: 'ETH',
    deadline: '2024-08-28',
    tags: ['Solidity', 'Internship', 'DeFi'],
    postedAt: '2024-07-28T12:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x14dc79964da2c08b23698b3d3cc7ca32193d9955',
  },
  {
    id: '10',
    title: 'Product Manager, Web3 Wallet',
    company: {
      name: 'EtherWallet',
      logoUrl: 'https://picsum.photos/seed/19/100/100',
      logoBg: 'bg-blue-500',
      logoIpfsCid: '',
    },
    description: 'Define the product roadmap for our industry-leading crypto wallet. A deep understanding of the user experience in Web3 is crucial.',
    budget: 19,
    currency: 'ETH',
    deadline: '2024-09-20',
    tags: ['Product Manager', 'UX', 'Web3'],
    postedAt: '2024-07-29T13:00:00Z',
    location: 'San Francisco, CA',
    status: 'Open',
    userId: '0x23618e81e3f5cdf7f54c3d65f7fbc0abf5b21e8f',
  },
  {
    id: '11',
    title: 'UI/UX Designer for dApps',
    company: {
      name: 'dApp Creations',
      logoUrl: 'https://picsum.photos/seed/20/100/100',
      logoBg: 'bg-lime-500',
      logoIpfsCid: '',
    },
    description: 'Create intuitive and beautiful interfaces for decentralized applications. A strong portfolio in web and mobile design is a must.',
    budget: 10,
    currency: 'ETH',
    deadline: '2024-09-18',
    tags: ['UI/UX', 'Design', 'Frontend'],
    postedAt: '2024-07-30T14:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0xa0ee7a142d267c1f36714e4a8f75612f20a79720',
  },
  {
    id: '12',
    title: 'Technical Writer (Blockchain)',
    company: {
      name: 'DocuChain',
      logoUrl: 'https://picsum.photos/seed/21/100/100',
      logoBg: 'bg-gray-500',
      logoIpfsCid: '',
    },
    description: 'Produce clear and concise documentation for our blockchain protocols and APIs. Ability to explain complex concepts to developers is key.',
    budget: 7,
    currency: 'ETH',
    deadline: '2024-09-02',
    tags: ['Content', 'Documentation'],
    postedAt: '2024-07-31T15:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0xbcd4042de499d14e55001ccbb24a551f3b954096',
  },
  {
    id: '13',
    title: 'QA Engineer for dApps',
    company: {
      name: 'QualityDefi',
      logoUrl: 'https://picsum.photos/seed/22/100/100',
      logoBg: 'bg-fuchsia-500',
      logoIpfsCid: '',
    },
    description: 'Ensure the quality of our decentralized applications through manual and automated testing. Experience with blockchain testing tools is a plus.',
    budget: 9,
    currency: 'ETH',
    deadline: '2024-09-08',
    tags: ['QA', 'Testing', 'DeFi'],
    postedAt: '2024-08-01T16:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x71be63f3384f5fb98995898a86e02fb04124cbc5',
  },
  {
    id: '14',
    title: 'Data Scientist (Crypto)',
    company: {
      name: 'CryptoData',
      logoUrl: 'https://picsum.photos/seed/23/100/100',
      logoBg: 'bg-sky-500',
      logoIpfsCid: '',
    },
    description: 'Analyze on-chain data to derive insights about user behavior and market trends. Strong background in statistics and machine learning.',
    budget: 21,
    currency: 'ETH',
    deadline: '2024-09-25',
    tags: ['Data Science', 'Analytics'],
    postedAt: '2024-08-02T10:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0xfabb0ac9d68b0b445fb7357272ff202c5651694a',
  },
  {
    id: '15',
    title: 'Marketing Lead (NFT Platform)',
    company: {
      name: 'NFT Galaxy',
      logoUrl: 'https://picsum.photos/seed/24/100/100',
      logoBg: 'bg-rose-500',
      logoIpfsCid: '',
    },
    description: 'Lead the marketing efforts for our new NFT platform. Proven experience in digital marketing and community building is required.',
    budget: 13,
    currency: 'ETH',
    deadline: '2024-09-14',
    tags: ['Marketing', 'Community', 'NFT'],
    postedAt: '2024-08-03T11:00:00Z',
    location: 'Los Angeles, CA',
    status: 'Open',
    userId: '0x1cbd3b2770909d4e10f157cabc84c7264073c9ac',
  },
  {
    id: '16',
    title: 'Move Developer (Sui/Aptos)',
    company: {
      name: 'MoveMakers',
      logoUrl: 'https://picsum.photos/seed/25/100/100',
      logoBg: 'bg-violet-500',
      logoIpfsCid: '',
    },
    description: 'We are looking for a developer with experience in the Move programming language to build on the Sui or Aptos ecosystems.',
    budget: 18,
    currency: 'ETH',
    deadline: '2024-09-22',
    tags: ['Blockchain', 'Move', 'Sui', 'Aptos'],
    postedAt: '2024-08-04T12:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0xcdf7028ceab81fa0c6971208e83fa7872994bee5',
  },
  {
    id: '17',
    title: 'React Native Engineer for Web3',
    company: {
      name: 'MobileChain',
      logoUrl: 'https://picsum.photos/seed/26/100/100',
      logoBg: 'bg-amber-500',
      logoIpfsCid: '',
    },
    description: 'Build our mobile crypto wallet using React Native. Experience with native modules and secure storage is a plus.',
    budget: 15,
    currency: 'ETH',
    deadline: '2024-09-28',
    tags: ['Mobile', 'React Native', 'Frontend'],
    postedAt: '2024-08-05T13:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x2546bcd3c84621e976d8185a91a922ae77ecec30',
  },
  {
    id: '18',
    title: 'Cryptography Researcher',
    company: {
      name: 'ZeroKnowledge Inc.',
      logoUrl: 'https://picsum.photos/seed/27/100/100',
      logoBg: 'bg-emerald-500',
      logoIpfsCid: '',
    },
    description: 'Join our research team to work on cutting-edge cryptography, including ZK-proofs and MPC. A PhD in a relevant field is preferred.',
    budget: 25,
    currency: 'ETH',
    deadline: '2024-10-01',
    tags: ['Research', 'Cryptography', 'ZK'],
    postedAt: '2024-08-06T14:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x02',
  },
  {
    id: '19',
    title: 'Legal Counsel (Web3)',
    company: {
      name: 'Lex Cryptographia',
      logoUrl: 'https://picsum.photos/seed/28/100/100',
      logoBg: 'bg-stone-500',
      logoIpfsCid: '',
    },
    description: 'Provide legal guidance on a range of issues in the Web3 space, including securities law, IP, and DAOs. Must be a licensed attorney.',
    budget: 24,
    currency: 'ETH',
    deadline: '2024-09-30',
    tags: ['Legal', 'DAO'],
    postedAt: '2024-08-07T15:00:00Z',
    location: 'Global',
    status: 'Open',
    userId: '0x03',
  },
  {
    id: '20',
    title: 'Head of Engineering',
    company: {
      name: 'Protocol Labs',
      logoUrl: 'https://picsum.photos/seed/29/100/100',
      logoBg: 'bg-indigo-600',
      logoIpfsCid: '',
    },
    description: 'Lead and scale our engineering team. You will be responsible for technical strategy, hiring, and mentorship.',
    budget: 30,
    currency: 'ETH',
    deadline: '2024-10-05',
    tags: ['Management', 'Full-Stack', 'Blockchain'],
    postedAt: '2024-08-08T16:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x04',
  },
  {
    id: '21',
    title: 'Zero-Knowledge Circuit Engineer',
    company: {
      name: 'ZK Circuits',
      logoUrl: 'https://picsum.photos/seed/30/100/100',
      logoBg: 'bg-pink-600',
      logoIpfsCid: '',
    },
    description: 'Design, implement, and optimize zero-knowledge circuits for privacy-preserving applications. Experience with Circom or Halo2 is required.',
    budget: 22,
    currency: 'ETH',
    deadline: '2024-09-26',
    tags: ['ZK', 'Cryptography', 'Solidity'],
    postedAt: '2024-08-09T10:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x05',
  },
  {
    id: '22',
    title: 'Gamer Economy Designer',
    company: {
      name: 'Metaverse Games',
      logoUrl: 'https://picsum.photos/seed/31/100/100',
      logoBg: 'bg-green-600',
      logoIpfsCid: '',
    },
    description: 'Design the tokenomics and in-game economy for our upcoming play-to-earn game. Strong understanding of game theory and economic modeling.',
    budget: 17,
    currency: 'ETH',
    deadline: '2024-09-19',
    tags: ['Gaming', 'Tokenomics', 'DeFi'],
    postedAt: '2024-08-10T11:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x06',
  },
  {
    id: '23',
    title: 'Node.js Developer for API Services',
    company: {
      name: 'APIConnect',
      logoUrl: 'https://picsum.photos/seed/32/100/100',
      logoBg: 'bg-red-600',
      logoIpfsCid: '',
    },
    description: 'Develop and maintain backend services and APIs that connect our users to the blockchain. Strong experience with Node.js and microservices.',
    budget: 13,
    currency: 'ETH',
    deadline: '2024-09-11',
    tags: ['Backend', 'Node.js', 'API'],
    postedAt: '2024-08-11T12:00:00Z',
    location: 'Berlin, Germany',
    status: 'Open',
    userId: '0x07',
  },
  {
    id: '24',
    title: 'Intern - Blockchain Research',
    company: {
      name: 'Future of Web3',
      logoUrl: 'https://picsum.photos/seed/33/100/100',
      logoBg: 'bg-yellow-600',
      logoIpfsCid: '',
    },
    description: 'Paid internship for a student or recent graduate to research emerging trends in blockchain technology, L2s, and DAOs.',
    budget: 5,
    currency: 'ETH',
    deadline: '2024-08-22',
    tags: ['Internship', 'Research', 'Blockchain'],
    postedAt: '2024-08-12T13:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x08',
  },
  {
    id: '25',
    title: 'Vyper Smart Contract Developer',
    company: {
      name: 'Curve Finance',
      logoUrl: 'https://picsum.photos/seed/34/100/100',
      logoBg: 'bg-cyan-600',
      logoIpfsCid: '',
    },
    description: 'Seeking a developer with expertise in Vyper to work on our core stablecoin swap protocols. Security is our top priority.',
    budget: 19,
    currency: 'ETH',
    deadline: '2024-09-24',
    tags: ['Vyper', 'Solidity', 'DeFi', 'Security'],
    postedAt: '2024-08-13T14:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x09',
  },
  {
    id: '26',
    title: 'GraphQL Specialist',
    company: {
      name: 'IndexerFi',
      logoUrl: 'https://picsum.photos/seed/14/100/100',
      logoBg: 'bg-yellow-500',
      logoIpfsCid: '',
    },
    description: 'We are seeking a GraphQL specialist to design and manage our data schemas for The Graph. You will work closely with the backend and frontend teams.',
    budget: 14,
    currency: 'ETH',
    deadline: '2024-09-16',
    tags: ['GraphQL', 'Backend', 'The Graph'],
    postedAt: '2024-08-14T15:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x10',
  },
  {
    id: '27',
    title: 'EVM Internals Expert',
    company: {
      name: 'EVM Deep Dive',
      logoUrl: 'https://picsum.photos/seed/35/100/100',
      logoBg: 'bg-purple-600',
      logoIpfsCid: '',
    },
    description: 'We need an expert with a deep understanding of the Ethereum Virtual Machine (EVM) to optimize our smart contracts for gas and performance.',
    budget: 23,
    currency: 'ETH',
    deadline: '2024-09-29',
    tags: ['EVM', 'Solidity', 'Optimization'],
    postedAt: '2024-08-15T16:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x11',
  },
  {
    id: '28',
    title: 'DAO Tooling Developer',
    company: {
      name: 'GovTools',
      logoUrl: 'https://picsum.photos/seed/36/100/100',
      logoBg: 'bg-orange-600',
      logoIpfsCid: '',
    },
    description: 'Build the next generation of tools for decentralized autonomous organizations (DAOs), including voting systems and treasury management.',
    budget: 16,
    currency: 'ETH',
    deadline: '2024-09-21',
    tags: ['DAO', 'Solidity', 'Full-Stack'],
    postedAt: '2024-08-16T10:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x12',
  },
  {
    id: '29',
    title: 'MEV Researcher',
    company: {
      name: 'Flashbots',
      logoUrl: 'https://picsum.photos/seed/37/100/100',
      logoBg: 'bg-teal-600',
      logoIpfsCid: '',
    },
    description: 'Research and develop strategies to mitigate the negative effects of Maximal Extractable Value (MEV). This is a research-heavy role.',
    budget: 20,
    currency: 'ETH',
    deadline: '2024-09-27',
    tags: ['MEV', 'Research', 'DeFi'],
    postedAt: '2024-08-17T11:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x13',
  },
  {
    id: '30',
    title: 'Web3 Gaming Unity Developer',
    company: {
      name: 'Pixel Play',
      logoUrl: 'https://picsum.photos/seed/38/100/100',
      logoBg: 'bg-blue-600',
      logoIpfsCid: '',
    },
    description: 'Integrate blockchain features into our Unity-based game. Experience with wallet connections and NFT standards (ERC-721/1155) is required.',
    budget: 15,
    currency: 'ETH',
    deadline: '2024-09-17',
    tags: ['Gaming', 'Unity', 'Frontend'],
    postedAt: '2024-08-18T12:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x14',
  },
  {
    id: '31',
    title: 'Technical Co-founder (DeFi)',
    company: {
      name: 'Stealth Startup',
      logoUrl: 'https://picsum.photos/seed/39/100/100',
      logoBg: 'bg-lime-600',
      logoIpfsCid: '',
    },
    description: 'Looking for a technical co-founder to build a new DeFi protocol from the ground up. Significant equity stake available for the right candidate.',
    budget: 28,
    currency: 'ETH',
    deadline: '2024-10-10',
    tags: ['Founder', 'DeFi', 'Full-Stack', 'Solidity'],
    postedAt: '2024-08-19T13:00:00Z',
    location: 'Global',
    status: 'Open',
    userId: '0x15',
  },
  {
    id: '32',
    title: 'Smart Contract Security Intern',
    company: {
      name: 'Guardian Audits',
      logoUrl: 'https://picsum.photos/seed/13/100/100',
      logoBg: 'bg-red-500',
      logoIpfsCid: '',
    },
    description: 'Internship focused on learning how to find vulnerabilities in smart contracts. You will work alongside our senior auditors.',
    budget: 6,
    currency: 'ETH',
    deadline: '2024-08-29',
    tags: ['Internship', 'Security', 'Audit', 'Solidity'],
    postedAt: '2024-08-20T14:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x16',
  },
  {
    id: '33',
    title: 'Layer 2 Scaling Solutions Architect',
    company: {
      name: 'ScaleUp',
      logoUrl: 'https://picsum.photos/seed/40/100/100',
      logoBg: 'bg-gray-600',
      logoIpfsCid: '',
    },
    description: 'Design and implement solutions using Layer 2 technologies like Optimistic and ZK-Rollups to scale our dApp.',
    budget: 26,
    currency: 'ETH',
    deadline: '2024-10-02',
    tags: ['L2', 'ZK', 'Optimism', 'Architecture'],
    postedAt: '2024-08-21T15:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x17',
  },
  {
    id: '34',
    title: 'Tokenomics Analyst',
    company: {
      name: 'Tokenomics Hub',
      logoUrl: 'https://picsum.photos/seed/41/100/100',
      logoBg: 'bg-fuchsia-600',
      logoIpfsCid: '',
    },
    description: 'Model and analyze token economic systems to ensure long-term sustainability and growth for our clients\' projects.',
    budget: 18,
    currency: 'ETH',
    deadline: '2024-09-23',
    tags: ['Tokenomics', 'Analytics', 'DeFi'],
    postedAt: '2024-08-22T16:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x18',
  },
  {
    id: '35',
    title: 'IPFS Infrastructure Engineer',
    company: {
      name: 'Decentralized Inc.',
      logoUrl: 'https://picsum.photos/seed/12/100/100',
      logoBg: 'bg-green-500',
      logoIpfsCid: '',
    },
    description: 'Manage and maintain our IPFS nodes and pinning services to ensure high availability and performance for decentralized storage.',
    budget: 14,
    currency: 'ETH',
    deadline: '2024-09-13',
    tags: ['IPFS', 'DevOps', 'Backend'],
    postedAt: '2024-08-23T10:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x19',
  },
  {
    id: '36',
    title: 'Head of Developer Relations',
    company: {
      name: 'DevRel Core',
      logoUrl: 'https://picsum.photos/seed/42/100/100',
      logoBg: 'bg-sky-600',
      logoIpfsCid: '',
    },
    description: 'Lead our developer relations team to build a strong community of developers around our protocol. Create tutorials, give talks, and gather feedback.',
    budget: 20,
    currency: 'ETH',
    deadline: '2024-09-28',
    tags: ['DevRel', 'Community', 'Marketing'],
    postedAt: '2024-08-24T11:00:00Z',
    location: 'Global',
    status: 'Open',
    userId: '0x20',
  },
  {
    id: '37',
    title: 'Zero-Knowledge Circuit Engineer',
    company: {
      name: 'Privacy Protocols',
      logoUrl: 'https://picsum.photos/seed/37/100/100',
      logoBg: 'bg-pink-600',
      logoIpfsCid: '',
    },
    description: 'Design and implement ZK circuits for privacy-preserving DeFi applications. Experience with Circom or Halo2 is required.',
    budget: 22,
    currency: 'ETH',
    deadline: '2024-10-15',
    tags: ['ZK', 'Cryptography', 'Solidity'],
    postedAt: '2024-08-25T10:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x21',
  },
  {
    id: '38',
    title: 'Gamer Economy Designer',
    company: {
      name: 'Pixel Realms',
      logoUrl: 'https://picsum.photos/seed/38/100/100',
      logoBg: 'bg-green-600',
      logoIpfsCid: '',
    },
    description: 'Design tokenomics for our play-to-earn game. Strong understanding of game theory and economic modeling is essential.',
    budget: 17,
    currency: 'ETH',
    deadline: '2024-10-12',
    tags: ['Gaming', 'Tokenomics', 'DeFi'],
    postedAt: '2024-08-26T11:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x22',
  },
  {
    id: '39',
    title: 'Node.js Developer for API Services',
    company: {
      name: 'BlockConnect',
      logoUrl: 'https://picsum.photos/seed/39/100/100',
      logoBg: 'bg-red-600',
      logoIpfsCid: '',
    },
    description: 'Develop and maintain backend services that connect our users to the blockchain. Strong experience with Node.js and microservices.',
    budget: 13,
    currency: 'ETH',
    deadline: '2024-10-08',
    tags: ['Backend', 'Node.js', 'API'],
    postedAt: '2024-08-27T12:00:00Z',
    location: 'Berlin, Germany',
    status: 'Open',
    userId: '0x23',
  },
  {
    id: '40',
    title: 'Intern - Blockchain Research',
    company: {
      name: 'Web3 Innovators',
      logoUrl: 'https://picsum.photos/seed/40/100/100',
      logoBg: 'bg-yellow-600',
      logoIpfsCid: '',
    },
    description: 'Paid internship for a student to research emerging trends in blockchain technology, L2s, and DAOs.',
    budget: 5,
    currency: 'ETH',
    deadline: '2024-09-30',
    tags: ['Internship', 'Research', 'Blockchain'],
    postedAt: '2024-08-28T13:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x24',
  },
  {
    id: '41',
    title: 'Vyper Smart Contract Developer',
    company: {
      name: 'StableSwap',
      logoUrl: 'https://picsum.photos/seed/41/100/100',
      logoBg: 'bg-cyan-600',
      logoIpfsCid: '',
    },
    description: 'Seeking a developer with expertise in Vyper to work on our core stablecoin swap protocols. Security is our top priority.',
    budget: 19,
    currency: 'ETH',
    deadline: '2024-10-20',
    tags: ['Vyper', 'Solidity', 'DeFi', 'Security'],
    postedAt: '2024-08-29T14:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x25',
  },
  {
    id: '42',
    title: 'GraphQL Specialist',
    company: {
      name: 'QueryVerse',
      logoUrl: 'https://picsum.photos/seed/42/100/100',
      logoBg: 'bg-yellow-500',
      logoIpfsCid: '',
    },
    description: 'Design and manage our data schemas for The Graph. You will work closely with the backend and frontend teams.',
    budget: 14,
    currency: 'ETH',
    deadline: '2024-10-10',
    tags: ['GraphQL', 'Backend', 'The Graph'],
    postedAt: '2024-08-30T15:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x26',
  },
  {
    id: '43',
    title: 'EVM Internals Expert',
    company: {
      name: 'DeepVM',
      logoUrl: 'https://picsum.photos/seed/43/100/100',
      logoBg: 'bg-purple-600',
      logoIpfsCid: '',
    },
    description: 'We need an expert with a deep understanding of the EVM to optimize our smart contracts for gas and performance.',
    budget: 23,
    currency: 'ETH',
    deadline: '2024-10-25',
    tags: ['EVM', 'Solidity', 'Optimization'],
    postedAt: '2024-08-31T16:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x27',
  },
  {
    id: '44',
    title: 'DAO Tooling Developer',
    company: {
      name: 'DAOWorks',
      logoUrl: 'https://picsum.photos/seed/44/100/100',
      logoBg: 'bg-orange-600',
      logoIpfsCid: '',
    },
    description: 'Build the next generation of tools for DAOs, including voting systems and treasury management.',
    budget: 16,
    currency: 'ETH',
    deadline: '2024-10-18',
    tags: ['DAO', 'Solidity', 'Full-Stack'],
    postedAt: '2024-09-01T10:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x28',
  },
  {
    id: '45',
    title: 'MEV Researcher',
    company: {
      name: 'Alpha Extractors',
      logoUrl: 'https://picsum.photos/seed/45/100/100',
      logoBg: 'bg-teal-600',
      logoIpfsCid: '',
    },
    description: 'Research and develop strategies to mitigate the negative effects of Maximal Extractable Value (MEV).',
    budget: 20,
    currency: 'ETH',
    deadline: '2024-10-22',
    tags: ['MEV', 'Research', 'DeFi'],
    postedAt: '2024-09-02T11:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x29',
  },
  {
    id: '46',
    title: 'Web3 Gaming Unity Developer',
    company: {
      name: 'Chain Arcade',
      logoUrl: 'https://picsum.photos/seed/46/100/100',
      logoBg: 'bg-blue-600',
      logoIpfsCid: '',
    },
    description: 'Integrate blockchain features into our Unity-based game. Experience with wallet connections and NFT standards is required.',
    budget: 15,
    currency: 'ETH',
    deadline: '2024-10-14',
    tags: ['Gaming', 'Unity', 'NFT', 'Frontend'],
    postedAt: '2024-09-03T12:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x30',
  },
  {
    id: '47',
    title: 'Technical Co-founder (DeFi)',
    company: {
      name: 'DeFi Next',
      logoUrl: 'https://picsum.photos/seed/47/100/100',
      logoBg: 'bg-lime-600',
      logoIpfsCid: '',
    },
    description: 'Looking for a technical co-founder to build a new DeFi protocol. Significant equity stake available.',
    budget: 28,
    currency: 'ETH',
    deadline: '2024-11-01',
    tags: ['Founder', 'DeFi', 'Full-Stack', 'Solidity'],
    postedAt: '2024-09-04T13:00:00Z',
    location: 'Global',
    status: 'Open',
    userId: '0x31',
  },
  {
    id: '48',
    title: 'Smart Contract Security Intern',
    company: {
      name: 'SecureBlock',
      logoUrl: 'https://picsum.photos/seed/48/100/100',
      logoBg: 'bg-red-500',
      logoIpfsCid: '',
    },
    description: 'Internship focused on learning how to find vulnerabilities in smart contracts. You will work with our senior auditors.',
    budget: 6,
    currency: 'ETH',
    deadline: '2024-10-05',
    tags: ['Internship', 'Security', 'Audit', 'Solidity'],
    postedAt: '2024-09-05T14:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x32',
  },
  {
    id: '49',
    title: 'Layer 2 Scaling Solutions Architect',
    company: {
      name: 'EthScaler',
      logoUrl: 'https://picsum.photos/seed/49/100/100',
      logoBg: 'bg-gray-600',
      logoIpfsCid: '',
    },
    description: 'Design and implement solutions using Layer 2 technologies like Optimistic and ZK-Rollups to scale our dApp.',
    budget: 26,
    currency: 'ETH',
    deadline: '2024-10-28',
    tags: ['L2', 'ZK', 'Optimism', 'Architecture'],
    postedAt: '2024-09-06T15:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x33',
  },
  {
    id: '50',
    title: 'Tokenomics Analyst',
    company: {
      name: 'CryptoEcon',
      logoUrl: 'https://picsum.photos/seed/50/100/100',
      logoBg: 'bg-fuchsia-600',
      logoIpfsCid: '',
    },
    description: 'Model and analyze token economic systems to ensure long-term sustainability and growth for our clients.',
    budget: 18,
    currency: 'ETH',
    deadline: '2024-10-19',
    tags: ['Tokenomics', 'Analytics', 'DeFi'],
    postedAt: '2024-09-07T16:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x34',
  },
  {
    id: '51',
    title: 'IPFS Infrastructure Engineer',
    company: {
      name: 'StorageChain',
      logoUrl: 'https://picsum.photos/seed/51/100/100',
      logoBg: 'bg-green-500',
      logoIpfsCid: '',
    },
    description: 'Manage and maintain our IPFS nodes and pinning services to ensure high availability for decentralized storage.',
    budget: 14,
    currency: 'ETH',
    deadline: '2024-10-09',
    tags: ['IPFS', 'DevOps', 'Backend'],
    postedAt: '2024-09-08T10:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x35',
  },
  {
    id: '52',
    title: 'Head of Developer Relations',
    company: {
      name: 'ConnectProtocol',
      logoUrl: 'https://picsum.photos/seed/52/100/100',
      logoBg: 'bg-sky-600',
      logoIpfsCid: '',
    },
    description: 'Lead our developer relations team to build a strong community. Create tutorials, give talks, and gather feedback.',
    budget: 20,
    currency: 'ETH',
    deadline: '2024-10-24',
    tags: ['DevRel', 'Community', 'Marketing'],
    postedAt: '2024-09-09T11:00:00Z',
    location: 'Global',
    status: 'Open',
    userId: '0x36',
  },
  {
    id: '53',
    title: 'Senior Frontend Engineer (React/Next.js)',
    company: {
      name: 'Web3Builders',
      logoUrl: 'https://picsum.photos/seed/53/100/100',
      logoBg: 'bg-indigo-500',
      logoIpfsCid: '',
    },
    description: 'We are seeking a senior frontend engineer to build out the user interface for our next-generation DeFi platform.',
    budget: 15,
    currency: 'ETH',
    deadline: '2024-10-30',
    tags: ['Frontend', 'React', 'Next.js', 'Web3'],
    postedAt: '2024-09-10T12:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x37',
  },
  {
    id: '54',
    title: 'Junior Blockchain Developer (Rust)',
    company: {
      name: 'Solana Ecosystem Fund',
      logoUrl: 'https://picsum.photos/seed/54/100/100',
      logoBg: 'bg-purple-500',
      logoIpfsCid: '',
    },
    description: 'An exciting opportunity for a junior developer to learn and build on the Solana ecosystem. Mentorship will be provided.',
    budget: 8,
    currency: 'ETH',
    deadline: '2024-10-21',
    tags: ['Blockchain', 'Rust', 'Solana', 'Internship'],
    postedAt: '2024-09-11T13:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x38',
  },
  {
    id: '55',
    title: 'Head of Product (NFT Marketplace)',
    company: {
      name: 'ArtBlock',
      logoUrl: 'https://picsum.photos/seed/55/100/100',
      logoBg: 'bg-pink-500',
      logoIpfsCid: '',
    },
    description: 'Define and execute the product strategy for a leading generative art NFT marketplace. A passion for art and technology is a must.',
    budget: 25,
    currency: 'ETH',
    deadline: '2024-11-05',
    tags: ['Product Manager', 'NFT', 'Art', 'Management'],
    postedAt: '2024-09-12T14:00:00Z',
    location: 'New York, NY',
    status: 'Open',
    userId: '0x39',
  },
  {
    id: '56',
    title: 'Data Analyst (Dune Analytics)',
    company: {
      name: 'On-Chain Insights',
      logoUrl: 'https://picsum.photos/seed/56/100/100',
      logoBg: 'bg-sky-500',
      logoIpfsCid: '',
    },
    description: 'Create and maintain dashboards on Dune Analytics to track key metrics for various DeFi protocols. Strong SQL skills are required.',
    budget: 11,
    currency: 'ETH',
    deadline: '2024-10-26',
    tags: ['Data Science', 'Analytics', 'SQL', 'DeFi'],
    postedAt: '2024-09-13T15:00:00Z',
    location: 'Remote',
    status: 'Open',
    userId: '0x40',
  },
];

export const jobCategories = [
  'All',
  'Frontend',
  'Backend',
  'Blockchain',
  'Solidity',
  'Full-Stack',
  'Security',
  'DeFi',
  'Remote',
  'Internship',
  'Gaming',
  'NFT',
  'DAO',
  'L2',
];
